import {
  ProgramRecord,
  TermRecord,
  CourseRecord,
  InstructorRecord,
  CourseAssignmentRecord,
  AssignmentComponentRecord,
  CalendarEventRecord,
  TaskRecord,
  TaskTemplateRecord,
  RecurringTaskRuleRecord,
  AdviseeRecord,
  PloRecord,
  CloRecord,
  CoursePloMapRecord,
  CloAssessmentMapRecord,
  CourseActivityRecord,
  AssessmentRecord,
  ContinuousImprovementRecord,
  AccreditationBodyRecord,
  AccreditationEvidenceRecord,
  CredentialRecord,
  ProgramFeatureRecord,
} from '../types';

export const INITIAL_PROGRAMS: ProgramRecord[] = [
  {
    'Program ID': 'PRG-CYBER',
    'Program Name': 'Cybersecurity & Information Assurance',
    'Program Code': 'CYB-BS',
    'Division': 'School of Technology & Applied Science',
    'CIP': '11.1003',
    'Status': 'Active',
    'Dean Email': 'dean.tech@institution.edu',
    'Created At': '2026-08-15T09:00:00',
    'Updated At': '2026-09-01T14:30:00',
  },
  {
    'Program ID': 'PRG-HIM',
    'Program Name': 'Health Information Management & Informatics',
    'Program Code': 'HIM-AAS',
    'Division': 'Allied Health Sciences',
    'CIP': '51.0707',
    'Status': 'Active',
    'Dean Email': 'dean.health@institution.edu',
    'Created At': '2026-08-15T09:00:00',
    'Updated At': '2026-09-01T14:30:00',
  },
];

export const INITIAL_TERMS: TermRecord[] = [
  {
    'Term ID': '2026AU',
    'Term Name': 'Autumn 2026',
    'Academic Year': '2026-2027',
    'Start Date': '2026-08-24',
    'End Date': '2026-12-18',
    'Status': 'Active',
  },
  {
    'Term ID': '2027SP',
    'Term Name': 'Spring 2027',
    'Academic Year': '2026-2027',
    'Start Date': '2027-01-11',
    'End Date': '2027-05-07',
    'Status': 'Upcoming',
  },
];

export const INITIAL_COURSES: CourseRecord[] = [
  {
    'Course ID': 'CRS-CYB101',
    'Program ID': 'PRG-CYBER',
    'Course Code': 'CYB 1010',
    'Course Title': 'Fundamentals of Information Security',
    'Credits': 3,
    'Term Placement': 'Year 1 / Term 1',
    'Length Weeks': 8,
    'Description': 'Core concepts of information security, CIA triad, threat modeling, and foundational defensive controls.',
    'Active': true,
    'Created At': '2026-08-15T10:00:00',
    'Updated At': '2026-09-01T11:00:00',
  },
  {
    'Course ID': 'CRS-CYB205',
    'Program ID': 'PRG-CYBER',
    'Course Code': 'CYB 2050',
    'Course Title': 'Network Defense & Countermeasures',
    'Credits': 4,
    'Term Placement': 'Year 1 / Term 2',
    'Length Weeks': 16,
    'Description': 'Architecting secure perimeters, firewall management, intrusion detection, packet inspection, and active defense.',
    'Active': true,
    'Created At': '2026-08-15T10:00:00',
    'Updated At': '2026-09-01T11:00:00',
  },
  {
    'Course ID': 'CRS-CYB220',
    'Program ID': 'PRG-CYBER',
    'Course Code': 'CYB 2200',
    'Course Title': 'Cloud Security & DevSecOps',
    'Credits': 3,
    'Term Placement': 'Year 2 / Term 1',
    'Length Weeks': 8,
    'Description': 'IAM policies, Zero Trust, cloud posture hardening, container security, and CI/CD vulnerability scanning.',
    'Active': true,
    'Created At': '2026-08-15T10:00:00',
    'Updated At': '2026-09-01T11:00:00',
  },
  {
    'Course ID': 'CRS-CYB290',
    'Program ID': 'PRG-CYBER',
    'Course Code': 'CYB 2900',
    'Course Title': 'Cybersecurity Capstone & Incident Response',
    'Credits': 3,
    'Term Placement': 'Year 2 / Term 2',
    'Length Weeks': 16,
    'Description': 'Comprehensive blue-team cyber defense simulation, incident response forensics, and professional synthesis.',
    'Active': true,
    'Created At': '2026-08-15T10:00:00',
    'Updated At': '2026-09-01T11:00:00',
  },
];

export const INITIAL_INSTRUCTORS: InstructorRecord[] = [
  {
    'Instructor ID': 'INS-DEP',
    'Program ID': 'PRG-CYBER',
    'Instructor Name': 'Prof. Norma DePriest',
    'Instructor Email': 'depriestn@hocking.edu',
    'Active': true,
    'Notes': 'Program Director; Lead Faculty for CYB 1010 & Capstone.',
    'Created At': '2026-08-15T10:00:00',
  },
  {
    'Instructor ID': 'INS-CHEN',
    'Program ID': 'PRG-CYBER',
    'Instructor Name': 'Dr. Marcus Chen',
    'Instructor Email': 'm.chen@institution.edu',
    'Active': true,
    'Notes': 'Network security and defensive perimeter specialist; CISSP certified.',
    'Created At': '2026-08-15T10:00:00',
  },
  {
    'Instructor ID': 'INS-MILLER',
    'Program ID': 'PRG-CYBER',
    'Instructor Name': 'Sarah Miller, M.S.',
    'Instructor Email': 's.miller@institution.edu',
    'Active': true,
    'Notes': 'Adjunct practitioner; Senior Cloud Security Architect.',
    'Created At': '2026-08-15T10:00:00',
  },
];

export const INITIAL_ASSIGNMENTS: CourseAssignmentRecord[] = [
  {
    'Assignment ID': 'ASN-001',
    'Program ID': 'PRG-CYBER',
    'Term ID': '2026AU',
    'Course ID': 'CRS-CYB101',
    'Section': '01',
    'Delivery Label': 'Standard',
    'Modality': 'Online Asynchronous',
    'Part of Term': '1st 8-Week Term',
    'Instructor Email': 'depriestn@hocking.edu',
    'Start Date': '2026-08-24',
    'End Date': '2026-10-16',
    'Status': 'Active',
  },
  {
    'Assignment ID': 'ASN-002',
    'Program ID': 'PRG-CYBER',
    'Term ID': '2026AU',
    'Course ID': 'CRS-CYB205',
    'Section': '01',
    'Delivery Label': 'Standard',
    'Modality': 'Hybrid',
    'Part of Term': 'Full Semester (16 Weeks)',
    'Instructor Email': 'm.chen@institution.edu',
    'Start Date': '2026-08-24',
    'End Date': '2026-12-18',
    'Status': 'Active',
  },
  {
    'Assignment ID': 'ASN-003',
    'Program ID': 'PRG-CYBER',
    'Term ID': '2026AU',
    'Course ID': 'CRS-CYB220',
    'Section': '01',
    'Delivery Label': 'Standard',
    'Modality': 'Online Asynchronous',
    'Part of Term': '2nd 8-Week Term',
    'Instructor Email': 's.miller@institution.edu',
    'Start Date': '2026-10-19',
    'End Date': '2026-12-18',
    'Status': 'Active',
  },
];

export const INITIAL_COMPONENTS: AssignmentComponentRecord[] = [
  {
    'Component ID': 'CMP-001',
    'Assignment ID': 'ASN-002',
    'Program ID': 'PRG-CYBER',
    'Component Type': 'Hands-on Cyber Lab',
    'Instructor Email': 'm.chen@institution.edu',
    'Modality': 'In-Person Lab',
    'Meeting Details': 'Tech Hall 204, Tuesdays 6:00-8:30 PM',
    'Active': true,
  },
];

export const INITIAL_PLOS: PloRecord[] = [
  {
    'PLO ID': 'PLO-01',
    'Program ID': 'PRG-CYBER',
    'PLO Number': 'PLO 1',
    'PLO Title': 'Threat Analysis & Defensive Architecture',
    'PLO Statement': 'Analyze complex technological ecosystems to identify vulnerabilities, formulate defensive postures, and apply mitigation controls in accordance with NIST cybersecurity frameworks.',
    'Active': true,
  },
  {
    'PLO ID': 'PLO-02',
    'Program ID': 'PRG-CYBER',
    'PLO Number': 'PLO 2',
    'PLO Title': 'Network Perimeter & Protocol Hardening',
    'PLO Statement': 'Configure and defend secure enterprise network architectures utilizing firewall ACLs, intrusion prevention systems, segmentations, and cryptographic tunnels.',
    'Active': true,
  },
  {
    'PLO ID': 'PLO-03',
    'Program ID': 'PRG-CYBER',
    'PLO Number': 'PLO 3',
    'PLO Title': 'Incident Response & Forensic Investigation',
    'PLO Statement': 'Execute systematic incident containment, digital forensic artifact preservation, and root-cause post-incident analytical documentation.',
    'Active': true,
  },
  {
    'PLO ID': 'PLO-04',
    'Program ID': 'PRG-CYBER',
    'PLO Number': 'PLO 4',
    'PLO Title': 'Ethics, Governance & Compliance',
    'PLO Statement': 'Formulate governance policies respecting legal, privacy, and regulatory requirements including HIPAA, FERPA, and PCI-DSS.',
    'Active': true,
  },
];

export const INITIAL_CLOS: CloRecord[] = [
  {
    'CLO ID': 'CLO-101-1',
    'Program ID': 'PRG-CYBER',
    'Course ID': 'CRS-CYB101',
    'CLO Number': 'CLO 1',
    'CLO Statement': 'Differentiate between confidentiality, integrity, and availability threat vectors.',
    'Assessment Method': 'Module 3 Threat Vector Quiz & Scenario Analysis',
    'Source / Approval': 'Curriculum Committee 2025',
    'Status': 'Active',
  },
  {
    'CLO ID': 'CLO-101-2',
    'Program ID': 'PRG-CYBER',
    'Course ID': 'CRS-CYB101',
    'CLO Number': 'CLO 2',
    'CLO Statement': 'Conduct basic host-level vulnerability scans using industry standard scanners.',
    'Assessment Method': 'Lab 4 Vulnerability Assessment Report',
    'Source / Approval': 'Curriculum Committee 2025',
    'Status': 'Active',
  },
  {
    'CLO ID': 'CLO-205-1',
    'Program ID': 'PRG-CYBER',
    'Course ID': 'CRS-CYB205',
    'CLO Number': 'CLO 1',
    'CLO Statement': 'Design an enterprise perimeter firewall rule matrix separating DMZ and internal subnets.',
    'Assessment Method': 'Midterm Firewall Configuration Project',
    'Source / Approval': 'Curriculum Committee 2025',
    'Status': 'Active',
  },
  {
    'CLO ID': 'CLO-205-2',
    'Program ID': 'PRG-CYBER',
    'Course ID': 'CRS-CYB205',
    'CLO Number': 'CLO 2',
    'CLO Statement': 'Analyze captured Wireshark pcap files to detect anomalous protocol behavior and exfiltration.',
    'Assessment Method': 'Final Packet Analysis Practical Exam',
    'Source / Approval': 'Curriculum Committee 2025',
    'Status': 'Active',
  },
];

export const INITIAL_COURSE_PLO_MAP: CoursePloMapRecord[] = [
  {
    'Mapping ID': 'CPM-001',
    'Program ID': 'PRG-CYBER',
    'Course ID': 'CRS-CYB101',
    'PLO ID': 'PLO-01',
    'Development Level': 'I',
    'Assessment Role': 'F',
    'Notes': 'Introduces foundational threat modeling and NIST security controls.',
  },
  {
    'Mapping ID': 'CPM-002',
    'Program ID': 'PRG-CYBER',
    'Course ID': 'CRS-CYB205',
    'PLO ID': 'PLO-02',
    'Development Level': 'R',
    'Assessment Role': 'S',
    'Notes': 'Summative measure for network defense and perimeter controls.',
  },
  {
    'Mapping ID': 'CPM-003',
    'Program ID': 'PRG-CYBER',
    'Course ID': 'CRS-CYB290',
    'PLO ID': 'PLO-03',
    'Development Level': 'R',
    'Assessment Role': 'S',
    'Notes': 'Capstone live incident response summative demonstration.',
  },
];

export const INITIAL_CLO_ASSESSMENT_MAP: CloAssessmentMapRecord[] = [
  {
    'Mapping ID': 'CAM-001',
    'Program ID': 'PRG-CYBER',
    'Course ID': 'CRS-CYB101',
    'CLO ID': 'CLO-101-1',
    'Assessment Name': 'Module 3 Threat Scenario Analysis',
    'Development Level': 'I',
    'Assessment Role': 'F',
    'Assessment Type': 'Case Study',
    'Notes': 'Formative assessment identifying security threat vectors.',
    'Active': true,
  },
  {
    'Mapping ID': 'CAM-002',
    'Program ID': 'PRG-CYBER',
    'Course ID': 'CRS-CYB101',
    'CLO ID': 'CLO-101-2',
    'Assessment Name': 'Host Vulnerability Assessment Practical',
    'Development Level': 'I',
    'Assessment Role': 'S',
    'Assessment Type': 'Lab Exam',
    'Notes': 'Summative assessment for CYB 1010 CLO 2.',
    'Active': true,
  },
  {
    'Mapping ID': 'CAM-003',
    'Program ID': 'PRG-CYBER',
    'Course ID': 'CRS-CYB205',
    'CLO ID': 'CLO-205-1',
    'Assessment Name': 'Midterm Enterprise Firewall Architecture',
    'Development Level': 'R',
    'Assessment Role': 'F',
    'Assessment Type': 'Hands-on Project',
    'Notes': 'Formative configuration test.',
    'Active': true,
  },
  {
    'Mapping ID': 'CAM-004',
    'Program ID': 'PRG-CYBER',
    'Course ID': 'CRS-CYB205',
    'CLO ID': 'CLO-205-2',
    'Assessment Name': 'Final Packet Analysis Practical Exam',
    'Development Level': 'R',
    'Assessment Role': 'S',
    'Assessment Type': 'Practical Examination',
    'Notes': 'Summative assessment verifying traffic anomaly detection.',
    'Active': true,
  },
];

export const INITIAL_ACTIVITIES: CourseActivityRecord[] = [
  {
    'Activity ID': 'ACT-001',
    'Program ID': 'PRG-CYBER',
    'Course ID': 'CRS-CYB101',
    'Week': '1',
    'Activity Name': 'Syllabus & Course Environment Verification',
    'Category': 'Orientation',
    'Grade Category': 'Participation',
    'Grade Weight': '2%',
    'Graded': 'Yes',
    'Individual/Group': 'Individual',
    'Major/Minor': 'Minor',
    'CLOs Supported': '',
    'Applied AI': 'No',
    'Portfolio Artifact': 'No',
    'Assessment Use': 'Practice Only',
    'Active': true,
  },
  {
    'Activity ID': 'ACT-002',
    'Program ID': 'PRG-CYBER',
    'Course ID': 'CRS-CYB101',
    'Week': '3',
    'Activity Name': 'Threat Model Case Study',
    'Category': 'Assignment',
    'Grade Category': 'Projects',
    'Grade Weight': '15%',
    'Graded': 'Yes',
    'Individual/Group': 'Individual',
    'Major/Minor': 'Major',
    'CLOs Supported': 'CLO 1',
    'Applied AI': 'Permitted with attribution',
    'Portfolio Artifact': 'Yes',
    'Credential Connection': 'CompTIA Security+ SY0-701 Domain 1',
    'Assessment Use': 'Formative',
    'Evidence Available': 'Yes',
    'Active': true,
  },
  {
    'Activity ID': 'ACT-003',
    'Program ID': 'PRG-CYBER',
    'Course ID': 'CRS-CYB101',
    'Week': '7',
    'Activity Name': 'Host Vulnerability Assessment Practical',
    'Category': 'Lab Exam',
    'Grade Category': 'Exams',
    'Grade Weight': '25%',
    'Graded': 'Yes',
    'Individual/Group': 'Individual',
    'Major/Minor': 'Major',
    'CLOs Supported': 'CLO 2',
    'Applied AI': 'Prohibited',
    'Portfolio Artifact': 'Yes',
    'Credential Connection': 'CompTIA Security+ SY0-701 Domain 2',
    'Assessment Use': 'Summative',
    'Evidence Available': 'Yes',
    'Active': true,
  },
];

export const INITIAL_ASSESSMENTS: AssessmentRecord[] = [
  {
    'Assessment ID': 'ASM-001',
    'Program ID': 'PRG-CYBER',
    'Course ID': 'CRS-CYB205',
    'PLO ID': 'PLO-02',
    'Measure': 'CYB 2050 Final Packet Anomaly Practical Evaluation',
    'Benchmark': '80% of students achieve ≥ 80% on the rubric.',
    'Result': '85.7% of cohort met benchmark (24 of 28 students).',
    'Finding': 'Strong comprehension of TCP/IP handshakes; slight weakness in identifying DNS tunneling exfiltration.',
    'Action Needed': 'Add dedicated hands-on lab in Week 9 focused on DNS tunneling signatures.',
    'Status': 'Action In Progress',
    'Rubric URL': 'https://drive.google.com/open?id=sample_rubric_plo2',
    'Evidence URL': 'https://drive.google.com/open?id=sample_evidence_plo2',
  },
];

export const INITIAL_TASKS: TaskRecord[] = [
  {
    'Task ID': 'TSK-001',
    'Program ID': 'PRG-CYBER',
    'Term ID': '2026AU',
    'Course ID': 'CRS-CYB101',
    'Assignment ID': 'ASN-001',
    'Owner Email': 'depriestn@hocking.edu',
    'Task Scope': 'Course',
    'Task Type': 'Semester Start',
    'Title': 'Verify LMS course shell and syllabus dates',
    'Description': 'Ensure all due dates in Blackboard/Canvas match the 1st 8-Week Term calendar.',
    'Status': 'READY',
    'Priority': 'High',
    'Due Date': '2026-08-21',
    'Generated': true,
    'Archived': false,
  },
  {
    'Task ID': 'TSK-002',
    'Program ID': 'PRG-CYBER',
    'Term ID': '2026AU',
    'Course ID': 'CRS-CYB205',
    'Assignment ID': 'ASN-002',
    'Owner Email': 'm.chen@institution.edu',
    'Task Scope': 'Course',
    'Task Type': 'Semester Start',
    'Title': 'Test Cyber Lab virtual machines & Wireshark images',
    'Description': 'Spin up lab sandbox containers to verify student access credentials and network isolation.',
    'Status': 'IN PROGRESS',
    'Priority': 'Critical',
    'Due Date': '2026-08-22',
    'Generated': true,
    'Archived': false,
  },
  {
    'Task ID': 'TSK-003',
    'Program ID': 'PRG-CYBER',
    'Owner Email': 'depriestn@hocking.edu',
    'Task Scope': 'Program',
    'Task Type': 'Accreditation',
    'Title': 'Assemble annual HLC criterion evidence for technology resources',
    'Description': 'Collect evidence of software licenses, lab infrastructure, and hardware refresh cycle.',
    'Status': 'TO DO',
    'Priority': 'Normal',
    'Due Date': '2026-09-30',
    'Generated': false,
    'Archived': false,
  },
  {
    'Task ID': 'TSK-004',
    'Program ID': 'PRG-CYBER',
    'Owner Email': 's.miller@institution.edu',
    'Task Scope': 'Instructor',
    'Task Type': 'Faculty Records',
    'Title': 'Submit annual AWS Academy educator accreditation verification',
    'Description': 'Upload renewed AWS Educator certificate to program faculty portfolio folder.',
    'Status': 'WAITING/BLOCKED',
    'Blocked Reason': 'Waiting on AWS Academy credential verification email.',
    'Priority': 'Normal',
    'Due Date': '2026-09-15',
    'Generated': false,
    'Archived': false,
  },
  {
    'Task ID': 'TSK-005',
    'Program ID': 'PRG-CYBER',
    'Course ID': 'CRS-CYB101',
    'Owner Email': 'depriestn@hocking.edu',
    'Task Scope': 'Course',
    'Task Type': 'Curriculum Review',
    'Title': 'Audit applied AI guidelines in course outline',
    'Description': 'Clarify allowable use of LLMs for code troubleshooting vs prohibited use during exams.',
    'Status': 'REVIEW NEEDED',
    'Priority': 'High',
    'Due Date': '2026-08-20',
    'Generated': false,
    'Archived': false,
  },
  {
    'Task ID': 'TSK-006',
    'Program ID': 'PRG-CYBER',
    'Course ID': 'CRS-CYB205',
    'Owner Email': 'm.chen@institution.edu',
    'Task Scope': 'Course',
    'Task Type': 'Grading',
    'Title': 'Publish first-week welcome announcement & expectations',
    'Description': 'Post course kickoff announcement introducing hybrid meeting schedule and required lab gear.',
    'Status': 'COMPLETE',
    'Priority': 'High',
    'Due Date': '2026-08-20',
    'Generated': true,
    'Archived': false,
  },
];

export const INITIAL_TASK_TEMPLATES: TaskTemplateRecord[] = [
  {
    'Template ID': 'TPL-START-01',
    'Program ID': 'PRG-CYBER',
    'Template Name': 'START-01',
    'Task Scope': 'Course',
    'Task Type': 'Semester Start',
    'Title': 'Verify instructor assignment & modality',
    'Description': 'Confirm the assigned instructor, section, modality, and part of term are correct in the LMS.',
    'Default Priority': 'High',
    'Repeat Type': 'None',
    'Default Day': '',
    'Applies To': 'Semester Start',
    'Active': true,
  },
  {
    'Template ID': 'TPL-START-02',
    'Program ID': 'PRG-CYBER',
    'Template Name': 'START-02',
    'Task Scope': 'Course',
    'Task Type': 'Semester Start',
    'Title': 'Confirm syllabus & approved course outline',
    'Description': 'Verify the current syllabus with approved CLOs is uploaded and visible to students.',
    'Default Priority': 'High',
    'Repeat Type': 'None',
    'Default Day': '',
    'Applies To': 'Semester Start',
    'Active': true,
  },
  {
    'Template ID': 'TPL-START-03',
    'Program ID': 'PRG-CYBER',
    'Template Name': 'START-03',
    'Task Scope': 'Course',
    'Task Type': 'Semester Start',
    'Title': 'Verify LMS gradebook setup & grading weights',
    'Description': 'Confirm gradebook categories, percentage weights, and assignment due dates align with syllabus.',
    'Default Priority': 'High',
    'Repeat Type': 'None',
    'Default Day': '',
    'Applies To': 'Semester Start',
    'Active': true,
  },
  {
    'Template ID': 'TPL-START-04',
    'Program ID': 'PRG-CYBER',
    'Template Name': 'START-04',
    'Task Scope': 'Course',
    'Task Type': 'Semester Start',
    'Title': 'Test links, labs, software, and external virtual tools',
    'Description': 'Open and test required technical tools, virtual lab links, and student license codes.',
    'Default Priority': 'High',
    'Repeat Type': 'None',
    'Default Day': '',
    'Applies To': 'Semester Start',
    'Active': true,
  },
  {
    'Template ID': 'TPL-START-05',
    'Program ID': 'PRG-CYBER',
    'Template Name': 'START-05',
    'Task Scope': 'Course',
    'Task Type': 'Semester Start',
    'Title': 'Confirm assessment/PLO collection obligations',
    'Description': 'Verify the course rubric and evidence collection requirement for designated program learning outcomes.',
    'Default Priority': 'Normal',
    'Repeat Type': 'None',
    'Default Day': '',
    'Applies To': 'Semester Start',
    'Active': true,
  },
  {
    'Template ID': 'TPL-WEEK-01',
    'Program ID': 'PRG-CYBER',
    'Template Name': 'WEEK-01',
    'Task Scope': 'Course',
    'Task Type': 'Weekly Operations',
    'Title': 'Review upcoming module & lab readiness',
    'Description': 'Review next week instructional unit, verify lab environments, and publish modules.',
    'Default Priority': 'Normal',
    'Repeat Type': 'Weekly',
    'Default Day': 'Friday',
    'Applies To': 'Weekly',
    'Active': true,
  },
  {
    'Template ID': 'TPL-WEEK-02',
    'Program ID': 'PRG-CYBER',
    'Template Name': 'WEEK-02',
    'Task Scope': 'Course',
    'Task Type': 'Weekly Operations',
    'Title': 'Review student engagement & risk alerts',
    'Description': 'Identify missing submissions, low participation, and notify academic advising.',
    'Default Priority': 'High',
    'Repeat Type': 'Weekly',
    'Default Day': 'Friday',
    'Applies To': 'Weekly',
    'Active': true,
  },
  {
    'Template ID': 'TPL-PROG-01',
    'Program ID': 'PRG-CYBER',
    'Template Name': 'PROG-01',
    'Task Scope': 'Program',
    'Task Type': 'Program Operations',
    'Title': 'Review program health dashboard & accreditation readiness',
    'Description': 'Review course coverage, assessment collection, advising logs, and continuous improvement items.',
    'Default Priority': 'High',
    'Repeat Type': 'Monthly',
    'Default Day': 'Monday',
    'Applies To': 'Program',
    'Active': true,
  },
  {
    'Template ID': 'TPL-INST-01',
    'Program ID': 'PRG-CYBER',
    'Template Name': 'INST-01',
    'Task Scope': 'Instructor',
    'Task Type': 'Faculty Operations',
    'Title': 'Confirm office hours and student support availability',
    'Description': 'Post current office hours, booking link, and messaging availability in all active shells.',
    'Default Priority': 'Normal',
    'Repeat Type': 'None',
    'Default Day': '',
    'Applies To': 'Instructor',
    'Active': true,
  },
];

export const INITIAL_RECURRING_RULES: RecurringTaskRuleRecord[] = [
  {
    'Rule ID': 'RCR-001',
    'Program ID': 'PRG-CYBER',
    'Task Scope': 'Course',
    'Term ID': '2026AU',
    'Course ID': 'CRS-CYB205',
    'Owner Email': 'm.chen@institution.edu',
    'Title': 'Grade weekly lab submissions & provide feedback',
    'Description': 'Complete grading for hands-on packet inspection labs within 5 days of submission.',
    'Frequency': 'Weekly',
    'Interval': 1,
    'Day of Week': 'Friday',
    'Start Date': '2026-08-28',
    'End Date': '2026-12-11',
    'Priority': 'Normal',
    'Status': 'TO DO',
    'Active': true,
  },
];

export const INITIAL_CALENDAR: CalendarEventRecord[] = [
  {
    'Calendar ID': 'CAL-001',
    'Program ID': 'PRG-CYBER',
    'Scope': 'GLOBAL',
    'Title': 'Autumn 2026 Full Semester Begins',
    'Category': 'Academic Calendar',
    'Start Date': '2026-08-24',
    'End Date': '2026-08-24',
    'All Day': true,
    'Description': 'First day of 16-week classes and 1st 8-Week Term.',
    'Status': 'Active',
  },
  {
    'Calendar ID': 'CAL-002',
    'Program ID': 'PRG-CYBER',
    'Scope': 'GLOBAL',
    'Title': 'Last Day to Add / Drop without "W"',
    'Category': 'Deadlines',
    'Start Date': '2026-09-01',
    'End Date': '2026-09-01',
    'All Day': true,
    'Description': 'Census date for Autumn enrollment reporting.',
    'Status': 'Active',
  },
  {
    'Calendar ID': 'CAL-003',
    'Program ID': 'PRG-CYBER',
    'Scope': 'Program',
    'Title': 'Cybersecurity Fall Advisory Board Meeting',
    'Category': 'Industry Advisory',
    'Start Date': '2026-09-17',
    'End Date': '2026-09-17',
    'All Day': false,
    'Description': 'Annual industry advisory review of curriculum, cloud credentials, and employer hiring trends.',
    'Status': 'Active',
  },
  {
    'Calendar ID': 'CAL-004',
    'Program ID': 'PRG-CYBER',
    'Scope': 'GLOBAL',
    'Title': 'Midterm Grade Submission Deadline',
    'Category': 'Grading',
    'Start Date': '2026-10-14',
    'End Date': '2026-10-14',
    'All Day': true,
    'Description': 'Midterm progress reports due in registrar portal.',
    'Status': 'Active',
  },
];

export const INITIAL_ADVISEES: AdviseeRecord[] = [
  {
    'Student ID': 'ADV-101',
    'Program ID': 'PRG-CYBER',
    'Student Name': 'Jordan Reynolds',
    'Student Email': 'jreynolds24@student.institution.edu',
    'Status': 'Enrolled (Full-time)',
    'Expected Graduation': 'Spring 2027',
    'Risk Flag': 'Good Standing',
    'Next Follow-Up': '2026-10-05',
    'Notes': 'Completed CompTIA Network+; working toward AWS Cloud Practitioner.',
  },
  {
    'Student ID': 'ADV-102',
    'Program ID': 'PRG-CYBER',
    'Student Name': 'Maria Santos',
    'Student Email': 'msantos@student.institution.edu',
    'Status': 'Enrolled (Part-time)',
    'Expected Graduation': 'Autumn 2027',
    'Risk Flag': 'Academic Alert',
    'Next Follow-Up': '2026-09-15',
    'Notes': 'Struggling with prerequisite networking concepts in CYB 2050; tutoring recommended.',
  },
];

export const INITIAL_BODIES: AccreditationBodyRecord[] = [
  {
    'Body ID': 'ACB-001',
    'Program ID': 'PRG-CYBER',
    'Body / Framework': 'Higher Learning Commission (HLC)',
    'Type': 'Institutional',
    'Required': 'Yes',
    'Review Cycle': '10 Years',
    'Next Review Date': '2028-03-15',
    'Standards URL': 'https://www.hlcommission.org/Criteria-Eligibility-and-Candidacy/criteria-for-accreditation.html',
    'Primary Contact': 'Vice President of Academic Affairs',
    'Status': 'Active',
    'Notes': 'Criterion 3: Teaching and Learning: Quality, Resources, and Support; Criterion 4: Assessment.',
  },
  {
    'Body ID': 'ACB-002',
    'Program ID': 'PRG-CYBER',
    'Body / Framework': 'NSA/DHS National Center of Academic Excellence (CAE-CD)',
    'Type': 'Programmatic / Specialized',
    'Required': 'Optional (Prestigious)',
    'Review Cycle': '5 Years',
    'Next Review Date': '2027-11-01',
    'Standards URL': 'https://www.caecommunity.org/',
    'Primary Contact': 'Prof. Norma DePriest',
    'Status': 'Active',
    'Notes': 'Knowledge Unit (KU) alignment and hands-on cyber lab criteria.',
  },
];

export const INITIAL_ACCREDITATION_EVIDENCE: AccreditationEvidenceRecord[] = [
  {
    'Evidence ID': 'ACE-001',
    'Program ID': 'PRG-CYBER',
    'Course ID': 'CRS-CYB205',
    'Bodies / Frameworks': 'HLC, CAE-CD',
    'Requirement / Standard': 'HLC 4.B - The institution demonstrates a commitment to educational achievement and improvement through ongoing assessment of student learning.',
    'Evidence Type': 'Assessment Report & Rubric Samples',
    'Title': 'CYB 2050 Network Security Direct Assessment Artifacts',
    'Description': 'Student anonymized submissions demonstrating network firewall rule design and vulnerability mitigations.',
    'Owner Email': 'depriestn@hocking.edu',
    'Due Date': '2026-10-30',
    'Status': 'Approved / Current',
    'Evidence URL': 'https://drive.google.com/open?id=evidence_hlc_4b',
    'Review Date': '2026-08-10',
    'Report Tags': 'HLC Criterion 4, CAE-CD KU-12',
  },
];

export const INITIAL_CREDENTIALS: CredentialRecord[] = [
  {
    'Credential ID': 'CRD-001',
    'Program ID': 'PRG-CYBER',
    'Course ID': 'CRS-CYB101',
    'Credential Name': 'CompTIA Security+ (SY0-701)',
    'Family': 'CompTIA Cybersecurity Pathway',
    'Provider': 'CompTIA',
    'Classification': 'Industry Certification',
    'Required/Optional': 'Embedded Curriculum / Highly Recommended',
    'Cost': 'Discounted Academic Voucher ($240)',
    'Status': 'Active Alignment',
    'URL': 'https://www.comptia.org/certifications/security',
  },
  {
    'Credential ID': 'CRD-002',
    'Program ID': 'PRG-CYBER',
    'Course ID': 'CRS-CYB220',
    'Credential Name': 'AWS Certified Security - Specialty',
    'Family': 'Amazon Web Services',
    'Provider': 'AWS',
    'Classification': 'Advanced Specialty Certification',
    'Required/Optional': 'Optional Milestone',
    'Cost': 'Voucher Provided through Tech Grant',
    'Status': 'Active Alignment',
    'URL': 'https://aws.amazon.com/certification/certified-security-specialty/',
  },
];

export const INITIAL_IMPROVEMENTS: ContinuousImprovementRecord[] = [
  {
    'Improvement ID': 'CIP-001',
    'Program ID': 'PRG-CYBER',
    'Source ID': 'ASM-001',
    'Issue/Finding': 'Students exhibited difficulty correlating DNS query logs with stealth exfiltration channels in CYB 2050.',
    'Action': 'Introduce interactive Wireshark DNS decoding lab and SIEM alert rules during Week 8.',
    'Owner Email': 'm.chen@institution.edu',
    'Target Date': '2026-10-15',
    'Status': 'In Progress',
    'Evidence URL': 'https://drive.google.com/open?id=cip_dns_lab',
  },
];

export const INITIAL_FEATURES: ProgramFeatureRecord[] = [
  { 'Feature ID': 'FTR-01', 'Program ID': 'PRG-CYBER', 'Feature Key': 'advising', 'Feature Label': 'Students & Advising', 'Enabled': true },
  { 'Feature ID': 'FTR-02', 'Program ID': 'PRG-CYBER', 'Feature Key': 'assessment', 'Feature Label': 'Assessment & Outcomes', 'Enabled': true },
  { 'Feature ID': 'FTR-03', 'Program ID': 'PRG-CYBER', 'Feature Key': 'accreditation', 'Feature Label': 'Accreditation Evidence', 'Enabled': true },
  { 'Feature ID': 'FTR-04', 'Program ID': 'PRG-CYBER', 'Feature Key': 'credentials', 'Feature Label': 'Industry Credentials', 'Enabled': true },
  { 'Feature ID': 'FTR-05', 'Program ID': 'PRG-CYBER', 'Feature Key': 'workforce', 'Feature Label': 'Workforce & Advisory Board', 'Enabled': true },
  { 'Feature ID': 'FTR-06', 'Program ID': 'PRG-CYBER', 'Feature Key': 'portfolio', 'Feature Label': 'Portfolio / Playbook', 'Enabled': true },
];

export function getFullInitialDataMap(): Record<string, Record<string, any>[]> {
  return {
    PROGRAMS: INITIAL_PROGRAMS,
    TERMS: INITIAL_TERMS,
    COURSES: INITIAL_COURSES,
    INSTRUCTOR_ROSTER: INITIAL_INSTRUCTORS,
    COURSE_ASSIGNMENTS: INITIAL_ASSIGNMENTS,
    ASSIGNMENT_COMPONENTS: INITIAL_COMPONENTS,
    PLOS: INITIAL_PLOS,
    COURSE_CLOS: INITIAL_CLOS,
    COURSE_PLO_MAP: INITIAL_COURSE_PLO_MAP,
    CLO_ASSESSMENT_MAP: INITIAL_CLO_ASSESSMENT_MAP,
    COURSE_ACTIVITIES: INITIAL_ACTIVITIES,
    ASSESSMENTS: INITIAL_ASSESSMENTS,
    TASKS: INITIAL_TASKS,
    TASK_TEMPLATES: INITIAL_TASK_TEMPLATES,
    RECURRING_TASK_RULES: INITIAL_RECURRING_RULES,
    ACADEMIC_CALENDAR: INITIAL_CALENDAR,
    ADVISEES: INITIAL_ADVISEES,
    ACCREDITATION_BODIES: INITIAL_BODIES,
    ACCREDITATION_EVIDENCE: INITIAL_ACCREDITATION_EVIDENCE,
    CREDENTIALS: INITIAL_CREDENTIALS,
    CONTINUOUS_IMPROVEMENT: INITIAL_IMPROVEMENTS,
    PROGRAM_FEATURES: INITIAL_FEATURES,
  };
}
